apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "openbanking.bank.labels" . | nindent 4 }}
  name: {{ template "openbanking.fullname" . }}-tls
{{ include "openbanking.namespace" . | indent 2 }}
stringData:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDfjCCAmagAwIBAgIUHOLlcMhX8uJyFafYYNXYBMBJr2swDQYJKoZIhvcNAQEL
    BQAwVzELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcT
    B1NlYXR0bGUxFDASBgNVBAoTC0Nsb3VkZW50aXR5MQswCQYDVQQLEwJDQTAeFw0y
    MTAxMjAwOTQ4MDBaFw0yNjAxMTkwOTQ4MDBaMFcxCzAJBgNVBAYTAlVTMRMwEQYD
    VQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdTZWF0dGxlMRQwEgYDVQQKEwtDbG91
    ZGVudGl0eTELMAkGA1UECxMCQ0EwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
    AoIBAQDKJroMoumr9jY129z7uf0WrvMxmzexP72ogINlQlM/p910YfnLYSWOUEIH
    kQ5eyq3ATuesPzamNxjq4JkafopsMBeieCeVzir4VTmsxLxbBZG2GjdsGpyXmrXb
    LXTb5dgNcolYh6LLPb11cBeb9TAy2D97Vx4t1Hr2SeLG1VvkNyNnoog6tZdmJUis
    ufW9GOyXgiAv46rtgvvpzYn+LbE7oiXlQHICHNpeTh7140HG7eWMPubINuilGZBY
    W80IGTpGUf2Vmuwo2LA17z5/3IB0dqlY5eT321TYVoqH1TYZrMllSLc+2x750e+l
    E9sHil8QPptAS74UWUsq2PgIvyZbAgMBAAGjQjBAMA4GA1UdDwEB/wQEAwIBBjAP
    BgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBTKWQeEZBRJ/UO1Py7EfTaOqVujbTAN
    BgkqhkiG9w0BAQsFAAOCAQEAsg5ker9FPcq1u5E+y4Qq1yjUeuOT0kap+aIE1mp2
    LSQoEA+tb40s/iNmTMdvCGReeoRoVYKz66+3zGoFYg5W1c5Ct9whjiLhKP1Pzc4I
    JbPGklSrnnAwD72ypLF4yrTMTD65gTMsr2ao0MOe6vy/Z8R2uz48QJHhhi71VGhi
    FstSiWvb4AgNhN39Ag5ufLtrGCbuZw5TSeW0J7PTBoYV1Z/0jrsdqxk8MjnbR8Qe
    VyZGyIRnGkXUtC239/Lz0v0PXVwAPUF8ITb0JYcG/ojIc5VfTOkQOeOHHBaS+dXt
    HBJjBbnwpN4tNFhczJkbga16hL+vV0I4z61mJG8OkDr25Q==
    -----END CERTIFICATE-----

  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIIEDjCCAvagAwIBAgIUFLUGb+Ux3LbyTAdP3Zskt0iCbQIwDQYJKoZIhvcNAQEL
    BQAwVzELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcT
    B1NlYXR0bGUxFDASBgNVBAoTC0Nsb3VkZW50aXR5MQswCQYDVQQLEwJDQTAeFw0y
    MTA0MjIwNzQ2MDBaFw0yNjA0MjEwNzQ2MDBaMHcxCzAJBgNVBAYTAlVTMRQwEgYD
    VQQIEwtXYXNoaW5naHRvbjEQMA4GA1UEBxMHU2VhdHRsZTEUMBIGA1UEChMLQ2xv
    dWRlbnRpdHkxFjAUBgNVBAsTDUF1dGhvcml6YXRpb24xEjAQBgNVBAMTCWFjcC5s
    b2NhbDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAK3L1G7VKO4aDacw
    DGA6IOncTgT0jIUltS+OSLH9ke5ltLfIKZ+bjdMYjv7LT9xOH9V9lI5HRMtMxbhD
    mLYy9+dybWLB15mcxm+z3lruhBMPS/ZxcGvDdZQILl3CUf3z6JfJFt7c3cXsJfcu
    vBoQJcTCoK7R1fA1RPeCKITAMcCE+Oab67mQhZDC7NLcmJ0UORKaeVhn2ghpiUIM
    iP+uhdCaAGs683P6Aoh0N1z1zsfrc6pJLm44I6E8cYUSt0Kh4gC8K4ivJiDEpZUV
    O6VFFzbGLpmDJtQ7sycQCTK9XnIC+JLDBi8tJL/JlkEzI8T7FDQnraVEpI+3XvKi
    WinKlZUCAwEAAaOBsTCBrjAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYB
    BQUHAwEGCCsGAQUFBwMCMAwGA1UdEwEB/wQCMAAwHQYDVR0OBBYEFGcYJd8n7Gcf
    cbvNVZgWPGnqJVqrMB8GA1UdIwQYMBaAFMpZB4RkFEn9Q7U/LsR9No6pW6NtMC8G
    A1UdEQQoMCaCCWxvY2FsaG9zdIIDYWNwgg5hY3AuYWNwLXN5c3RlbYcEfwAAATAN
    BgkqhkiG9w0BAQsFAAOCAQEAcm30fGxCWVpR+VRkF2nmnCtY6ksWT27eb5ZppsNs
    CoAwT9EMaRRQ3sx43/TvvdpxzJKcCHmdPLROgg/L5UMmOMjGT5mqcEvF8CiyAT/g
    pY1iuwqIbp3sSfnyTiQnGpSzHfvUsaOgkcFrLkC8lYLLal7aHSP5On3y+PMh8mdm
    DJSKt973VQj87q4qE9iDXdpzj0K5MKS+sbNOiOH8If9I2TqMcqwdrrLe/VP7mhz6
    oNc+cr++xId6h1jO768jq0OiK5G/oQQXZPD/wL+TXF0W/dw6F58EwHeQcD/H7wAs
    Z1hQb51e/+bSJxWMogTVPTEClXz0NpMIV9Xrcxfhk71Rjw==
    -----END CERTIFICATE-----

  tls.key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpQIBAAKCAQEArcvUbtUo7hoNpzAMYDog6dxOBPSMhSW1L45Isf2R7mW0t8gp
    n5uN0xiO/stP3E4f1X2UjkdEy0zFuEOYtjL353JtYsHXmZzGb7PeWu6EEw9L9nFw
    a8N1lAguXcJR/fPol8kW3tzdxewl9y68GhAlxMKgrtHV8DVE94IohMAxwIT45pvr
    uZCFkMLs0tyYnRQ5Epp5WGfaCGmJQgyI/66F0JoAazrzc/oCiHQ3XPXOx+tzqkku
    bjgjoTxxhRK3QqHiALwriK8mIMSllRU7pUUXNsYumYMm1DuzJxAJMr1ecgL4ksMG
    Ly0kv8mWQTMjxPsUNCetpUSkj7de8qJaKcqVlQIDAQABAoIBAQCsgTb4U8funhmT
    KxP9p3Tn623daUbZGhZ/f4EUepYQxQ7dpGX8MJBTSXsV2IQKLdlXNPDxUDgueqN+
    REod/vUl2+RLNBBmPsCQOz6njzu1F2fU08A8lqPsLTqogaqUoTbrAgQbbasLO1xr
    vw2h6Qk0BeMr4sexR46PBbhmG8bGSRM/F+2lJKwrLdoBamJBrax0s33QXHJzE401
    Mbp0APSOr/8Sl7NGeAK6bjBKZgD6PjCRFvgTPH4N8IXUKcro25glpwT8AQAvpB2N
    hnULvGpElbMEcHYRz86Mjf/7zdIjaRx0/3dK87bmI3MrReNaJv1U+ne/lslPJizU
    mXbV1mABAoGBANl8OkIzRI0JmC4DN/QP0DCEmQMvE1vkR3rhRQMCeWPWn8E+17T4
    pOW+ffKEnT5paRmZrw9X3I79OEBrVErZYFNf6f33DMjB11bzs6KQF+N0if2NlSf9
    RMOOrbIKeg0+FRuDTxJX0VY+mjw7xfzRq7Zg+zLSdyTHbymvtLfyVrmVAoGBAMyS
    8X3WSYKLVKEkDH4IEz/Ohf9BvpS7f2lSr9VeK820WYJDKbVi5W+Usjr0/KR8dAgR
    qJdki3I4PQEwGT3ABcYg8Dv9/hdRSx+KV9oCPctA1pKG2eAiZkSXYePDZANU3SNw
    9SLMFWT7AENRmrbSZoxZh79c3RBu9SWYaaAsRWwBAoGBALUuRcaCuVgZpxql+cYs
    Kk9RF7vMSv9htJ7M7lYsiH5A/YPa247bGVyADqKsEec9n54BJxLMKmVA1Mzt3SIh
    55ptrByz5IWW3tOEYKFME2qc2pxNh/Xxi4iy40cQbU986c6q3IO2fyGvM4R8c1tE
    PR3Ju1tCdJlCP/xlcVNQ4yjlAoGBAKTDKIpv/w6MByItdX5AJLi8LgHSwprplAmQ
    1hsj2GW5fmnCjCIRv7YpbY68Z4pWzeD9z+n2ybS5hLCjO4EXWc8kEjhPLck76SRC
    +NSV/4zm8Kpcv7ecHP/baLTXVoK0Y9K6lERtWEHXQnP1koTyWjNpnEJMmaM1qm2Y
    HmIppdQBAoGAUbEDiujATPO8XVFqFPcFp4qHKlWFEraBc4Tesk1w1rDN6vIrT8Vh
    U78GmaVTXcGTrMt8QBt6fFUVbVpuW2Cf/aDH/6UelkwsobZaWQy58d2Nv0NSkguO
    DbIu9KRAOP+2TVg8uTYg1Y+PqAuAbQAauYpc+wb48EbMgXx1a294fuI=
    -----END RSA PRIVATE KEY-----
