## ACP-CD image parameters
##
image:
  ## Image repository
  ##
  repository: docker.cloudentity.io/acp

  ## Image pull policy
  ##
  pullPolicy: IfNotPresent

  ## Image tag (immutable tags are recommended, default is the chart appVersion)
  ##
  tag: ""

## Global Docker registry secret names as an array
##
imagePullSecrets:
  - name: docker.cloudentity.io

## Credentials for your ACP-CD
##
##
clientCredentials:

  create: true

  name: ""

  clientID: "YnZnN2h2YzA1NnV0YmdpaHF1OWcK"
  clientSecret: "aE0wdmYwZHNBMHkxSHBHZW1WXzlDa21iYmlOclp2NW92S1JDTm5hd2pJbwo="
  issiuerURL: "https://acp.acp-system:8443/default/system"

policies:
  - tenant_id: "{tid}"
    server_id: "{aid}"
    id: block_test_policy
    policy_name: block_test
    language: cloudentity
    type: api
    validators:
      - name: "false"
  - tenant_id: "{tid}"
    server_id: "{aid}"
    id: allow_test_policy
    policy_name: allow_test
    language: cloudentity
    type: api
    validators:
      - name: "true"
gateway_api_groups:
  - tenant_id: "{tid}"
    server_id: "{aid}"
    service_id: httpbin
    gateway_id: sample-istio-authorizer
    name: "default/httpbin"
    id: test
    apis:
      - method: GET
        path: /deny
      - method: GET
        path: /anything
services:
  - id: httpbin
    tenant_id: "{tid}"
    authorization_server_id: "{aid}"
    gateway_id: sample-istio-authorizer
    name: default/httpbin
    apis:
      - method: GET
        path: /deny
        can_have_policy: true
        policy_id: block_test_policy
      - method: GET
        path: /anything
        can_have_policy: true
        policy_id: allow_test_policy   