engines:
  node: v18
dependencies:
  async: 3.2.4
  aws-sdk: 2.1404.0
  axios: 1.5.1
  axios-retry: 3.8.0
  async-lock: 1.4.0
  body-parser: 1.20.1
  chalk: 5.2.0
  co: 4.6.0
  debug: 4.3.4
  express: 4.18.2
  express-timeout-handler: 2.2.2
  graphql: 16.8.1
  immutable: 4.2.2
  invariant: 2.2.4
  js-yaml: 4.1.0
  jsonwebtoken: 9.0.0
  ldapjs: 2.3.3
  lodash: 4.17.21
  log4js: 6.7.1
  lru_map: 0.4.1
  minimist: 1.2.7
  mongodb: 5.6.0
  mongoose: 7.4.1
  morgan: 1.10.0
  mysql: 2.18.1
  mz: 2.7.0
  node-fetch: 3.3.0
  qs: 6.11.0
  ramda: 0.28.0
  rxjs: 7.8.0
  uglify-js: 3.17.4
  underscore: 1.13.6
  uuid: 9.0.0
  validator: 13.7.0
  ws: 8.12.0
  xml2js: 0.6.0
