engines:
  node: v18
dependencies:
  async: 3.2.6
  async-lock: 1.4.1
  aws-sdk: 2.1541.0
  axios: 1.7.4
  axios-retry: 4.0.0
  body-parser: 1.20.3
  chalk: 5.3.0
  co: 4.6.0
  debug: 4.3.4
  express: 4.21.2
  express-timeout-handler: 2.2.2
  graphql: 16.8.1
  immutable: 4.3.4
  invariant: 2.2.4
  js-yaml: 4.1.0
  jsonwebtoken: 9.0.2
  ldapjs: 3.0.7
  lodash: 4.17.21
  log4js: 6.9.1
  lru_map: 0.4.1
  minimist: 1.2.8
  mongodb: 6.3.0
  mongoose: 8.8.4
  morgan: 1.10.0
  mysql: 2.18.1
  mz: 2.7.0
  node-fetch: 3.3.2
  qs: 6.11.2
  ramda: 0.29.1
  rxjs: 7.8.1
  uglify-js: 3.17.4
  underscore: 1.13.6
  uuid: 9.0.1
  validator: 13.11.0
  ws: 8.18.0
  xml2js: 0.6.2
