{{- if .Values.discovery.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "istio-authorizer.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "istio-authorizer.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: ""
  kind: ClusterRole
  name: {{ include "istio-authorizer.serviceAccountName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "istio-authorizer.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}