apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "istio-authorizer.serviceAccountName" . }}
  labels:
    {{- include "istio-authorizer.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
- apiGroups:
  - ""
  resources:
  - "namespaces"
  verbs:
  - "list"
- apiGroups:
  - "apps"
  resources:
  - "deployments"
  verbs:
  - "list"
