apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: docker.cloudentity.io
data:
  .dockerconfigjson: eyJhdXRocyI6eyJkb2NrZXIuY2xvdWRlbnRpdHkuaW8iOnsidXNlcm5hbWUiOiJhdXRob3JpemVycyIsInBhc3N3b3JkIjoiek0zRjMzSWZWWWx5Q3BCZUVpUkxYN0tpc0RHU2plUVkiLCJhdXRoIjoiWVhWMGFHOXlhWHBsY25NNmVrMHpSak16U1daV1dXeDVRM0JDWlVWcFVreFlOMHRwYzBSSFUycGxVVms9In19fQ==
