{{- range splitList "," .Values.discovery.namespaces -}}
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: acp-authorizer
  namespace: {{ . }}
spec:
  action: CUSTOM
  provider:
    name: acp-authorizer
  rules:
  - {}
{{- end }}
