{{- range .Values.discovery.namespaces -}}
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: acp-istio-authorizer-policy
  namespace: {{ . }}
spec:
  action: CUSTOM
  provider:
    name: acp-authorizer
  rules:
  - {}
---
{{- end }}
