{{- if .Values.clientSecret.create -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "istio-authorizer.clientSecretName" . }}
  labels:
    {{- include "istio-authorizer.labels" . | nindent 4 }}
data:
  clientID: {{ .Values.clientSecret.clientID }}
  clientSecret: {{ .Values.clientSecret.clientSecret }}
{{- end }}
