{{- if .Values.clientCredentials.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "istio-authorizer.clientCredentialsName" . }}
  labels:
    {{- include "istio-authorizer.labels" . | nindent 4 }}
stringData:
  clientID: {{ .Values.clientCredentials.clientID }}
  clientSecret: {{ .Values.clientCredentials.clientSecret }}
{{- end }}
