apiVersion: v1
kind: Service
metadata:
  name: {{ include "istio-authorizer.fullname" . }}
  labels:
    {{- include "istio-authorizer.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 9001
      name: grpc
    - port: 9002
      name: http
  selector:
    {{- include "istio-authorizer.selectorLabels" . | nindent 4 }}
