{{- if and .Values.consentSelfservice.enabled .Values.serviceAccounts.consentSelfservice.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "openbanking.consentSelfservice.labels" . | nindent 4 }}
  name: {{ template "openbanking.serviceAccountName.consentSelfservice" . }}
{{ include "openbanking.namespace" . | indent 2 }}
  annotations:
{{ toYaml .Values.serviceAccounts.consentSelfservice.annotations | indent 4 }}
{{- end -}}
