{{- if and .Values.bank.enabled .Values.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ template "openbanking.bank.fullname" . }}
  labels:
    {{- include "openbanking.labels" . | nindent 4 }}
spec:
  commonName: bank
  subject:
    organizationalUnits: [ Authorization ]
    organizations: [ Cloudentity ]
    localities: [ Seattle ]
    provinces: [ Washinghton ]
    countries: [ US ]
  dnsNames:
    - {{ template "openbanking.bank.fullname" . }}
    - {{ template "openbanking.bank.fullname" . }}.{{ .Release.Namespace }}
    - {{ template "openbanking.bank.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
    {{- with .Values.certManager.extraNames }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  secretName: {{ template "openbanking.bank.fullname" . }}-tls
  issuerRef:
    name: {{ .Values.certManager.clusterIssuer | default "ca-issuer" }}
    kind: {{ .Values.certManager.kind | default "ClusterIssuer" }}
{{- end }}
