{{- if and .Values.bank.enabled (not .Values.certManager.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "openbanking.bank.labels" . | nindent 4 }}
  name: {{ template "openbanking.bank.fullname" . }}-tls
{{ include "openbanking.namespace" . | indent 2 }}
stringData:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIC+TCCAeGgAwIBAgIJAKPGwKDl/5HnMA0GCSqGSIb3DQEBCwUAMBMxETAPBgNV
    BAMMCGpvc2h2YW5sMB4XDTE5MDgyMjE2MDU1OFoXDTI5MDgxOTE2MDU1OFowEzER
    MA8GA1UEAwwIam9zaHZhbmwwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
    AQCwhSB/qW6/kLb2zpu+EJvD9wHFaq+QA/0JH/Lllyo7zAFx+HHq+COAbk+C8B4t
    /HUEsns5RL09CZ+X4j6pbJFdKduPxXu5ZVYnkxYpUDU7yg7OSKSZzTnIZ723sMs0
    R6jYn/Drj4xXMJEfHUDqYeSWlZr3qi1EFa0c7fVDxH+4xtZtNNFOjH7c6D/vWkIg
    WQUxiwusse6KMOWjDnv/4Vrjel2QgUYUbHCyeZHmcti+K0LWCfo/Rg6PulwrbDkh
    jmOgYt30pdhX0OZkAuklfUDHfp8bjbCoI2taYABA6AKjKsO35LAEU79CL1mLVHuZ
    ACI5Ujija3VPWVHSwmJPJyuxAgMBAAGjUDBOMB0GA1UdDgQWBBQml5dTAZixFKhj
    93wucRWhao/tQjAfBgNVHSMEGDAWgBQml5dTAZixFKhj93wucRWhao/tQjAMBgNV
    HRMEBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQB+klkRNJUKBLX8yYkyuU2RHcBv
    GhmmDjJIsOJHZsoYXdLlG1pZNFjjPaOL8vh44Vl98RhEZBHsLT1KMbp1su6Cqj0r
    UG1kpRBef+IOMT4MU7vRICi7UOlRLp1Wp0F8la3hPOcRb2yOfFqXXyZWXf4t0B45
    tHi+ZCNHB9FxjSRycbGYVk+TKpvhJaSYNMGJ3dxDKaP7+Dx3XcK6sAnIAkhyI8aj
    NU+mw8/tmRkP4In/kXAR+Ri0qUmHj/vwvnk4Km7ZUy1FYH8DMeS5Nksn+/uHlRxR
    V7Dnn039TRmgKbAqN72gKNLo5cZ+y/YqDAYHYrn98SQT9JDgtI/K/ATpW8dX
    -----END CERTIFICATE-----

  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDxzCCAq+gAwIBAgIQD3AfZmm1MZWVHcq/Gp1rrTANBgkqhkiG9w0BAQsFADAT
    MREwDwYDVQQDDAhqb3NodmFubDAeFw0yMTA2MTAyMjIwMzFaFw0yMTA5MDgyMjIw
    MzFaMHIxCzAJBgNVBAYTAlVTMRQwEgYDVQQIEwtXYXNoaW5naHRvbjEQMA4GA1UE
    BxMHU2VhdHRsZTEUMBIGA1UEChMLQ2xvdWRlbnRpdHkxFjAUBgNVBAsTDUF1dGhv
    cml6YXRpb24xDTALBgNVBAMTBGJhbmswggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAw
    ggEKAoIBAQCjzAbBX2wLYvTuh0Zq744Wam2U9E49Iu+7rBBxiUum+G+Abok60nBx
    Hocr6kkOHX75OMn8vT3dez3TDSursiHUAk2sz89BEd0gyMNZl6tgHdhtglOZgNr4
    XGsxafr6JPazYY7Y9MRctdmc67PuW4iwQCI5+xwRsAOe0jY11PojoJi+vczYs1do
    FuzVuiHjl1nDK441X5FXmZ3skVZx563b1lSvxr1OWC82V24PrLvYZVIsdFO+skV7
    YZIctku/hHYOCCBF+e5kayBLxnvhh+6lSTsTnUVoknn+kW5ADwR/Z6rKCRPqLu9c
    BVh+ZnMiyt/It8BaYNdQ3OkOHI0k97zLAgMBAAGjgbcwgbQwDgYDVR0PAQH/BAQD
    AgWgMAwGA1UdEwEB/wQCMAAwHwYDVR0jBBgwFoAUJpeXUwGYsRSoY/d8LnEVoWqP
    7UIwcwYDVR0RBGwwaoIUeHh4LW9wZW5iYW5raW5nLWJhbmuCH3h4eC1vcGVuYmFu
    a2luZy1iYW5rLmFjcC1zeXN0ZW2CMXh4eC1vcGVuYmFua2luZy1iYW5rLmFjcC1z
    eXN0ZW0uc3ZjLmNsdXN0ZXIubG9jYWwwDQYJKoZIhvcNAQELBQADggEBAFCriUMj
    vKJ1f5mRFKdowReudu+LWZGyWamVbd3js9R9FlaDDylzUcFi7bI0lE1yp2dlSzvR
    BBwA5HGKT7SsPcDtJh4ncE+GCLpaRvrAFnHgXRezF8pLN53CywzSz5wSJ9IyyYPv
    Qdp0RgY9juauRr6j2ShKosTapd6vJynKvZ/NjOU4/PxXc+jh6zEJt1te21pud1XA
    LKY6QG1jxhzXm6+bdEFV9yMzbFbW17T39icg1IYM7GVfPAwJZ+Pm+TxsCv4hQucZ
    EoSU/SiLzTJnRAl+RAwR0dQ9UcJHkTG5pePoxglFlmo9Mgspm6h3M2CdUudLJp0d
    JjFaSnJQxXq3img=
    -----END CERTIFICATE-----

  tls.key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpQIBAAKCAQEAo8wGwV9sC2L07odGau+OFmptlPROPSLvu6wQcYlLpvhvgG6J
    OtJwcR6HK+pJDh1++TjJ/L093Xs90w0rq7Ih1AJNrM/PQRHdIMjDWZerYB3YbYJT
    mYDa+FxrMWn6+iT2s2GO2PTEXLXZnOuz7luIsEAiOfscEbADntI2NdT6I6CYvr3M
    2LNXaBbs1boh45dZwyuONV+RV5md7JFWceet29ZUr8a9TlgvNlduD6y72GVSLHRT
    vrJFe2GSHLZLv4R2DgggRfnuZGsgS8Z74YfupUk7E51FaJJ5/pFuQA8Ef2eqygkT
    6i7vXAVYfmZzIsrfyLfAWmDXUNzpDhyNJPe8ywIDAQABAoIBAQCE0CaaHVlqUi7w
    Slfa1auMmXeJVB8si2t/7SDYLs9c8AzZQsebHo916Z8JCMt72obeZiHCAWBsekXD
    H+bNLX8ofUWmXkpbJLT8pE1iFA0tvoWDJi3LRiRHRgjU5G5Q7i/re6tsV+vwkLOG
    /cfD+gx3fUlDYk18OhB1c1XpiGva/kz6CkUj0ecY/iWTL+iKu5q9yvnIOqBo2KbT
    c5sMn4hNtDEUp4PD8zfHo+XNdLM3WWXFnaGpCU4qjbClmXR6KtKB0ZRSoMTvMNq3
    0c2SOWHbQ0tnBupNyS1TvbxSOBzLHya2//USrTdwh2gXWSFrQgCd1m8KjyDMqjJk
    Muv4sZEBAoGBAMQ4ubA40bi4udNCNxmu/7ubpj8Uaqcdt05SkEcQd3jU3IK+9ptg
    yEhCXBy8HtnWOAJbG7Wwaq6QIhyMV5zlzPbm35UZt7k1akvgJAlcNNSJi7RTQvu2
    gWIPUooUccqspnhAcsehyZki+SuAJLJqON2nldoDeigMUQBqaKH37rBrAoGBANWy
    g4ctP+Sov4SYNN/1DxCDpEIu5/ZoPf+cptOavAKhcMxKYF2IPwI0xL0Ov7EynlL2
    p8z7+m/XIX+bYdBhvv1KU0/5ktqsXUIQCt0t5v9qoCVyWz61WFuRO4m8ts09x5r9
    LJBeqSgQKZkLlfBpeGsmoP/eAsh+NO3ei+7R3L0hAoGBAI9ozf3HaS/Sgq2uJUs2
    JV3eYmCT8Wb2RvSNTzlBBbBgElHUc7QXxglZxqyRqRKYiBLgt53QtAek++lVgOsA
    4Q5Kqnn0c9x+95NA29WjeFElvd8rQzdoqaMbg727N3djO7+Dit/wlMDBWM68NxXW
    oH0PcGwIQo1mgwUEwDgwVljFAoGASBgno40yhxQfOL6Y6A2m/W1MFz/35fuZHwlc
    hvsm/sQ0Z9eX1zZF+5qN3TKCnWd0Xoz0Y4WHIgA0PvbO8xxm8NEIdmy+jKOl+smq
    wJ/h1L3GNZv1CJzpqErBCWDvUyLKmpFbXYFyFCAPyKBN/4O1qoCnxGrECZv6g12X
    XATVMcECgYEAubYpGPW/3KanCvNqS8FqlU6vBlfpxlqtmd5xv/0eje8wROTq7gE7
    F2m/YzpKHB1EowotIf8NKO3H0Sm15BNA3j9YOQUMb8pl9Y7sLwz8D9w2ACkU4fVQ
    iZPWh/Plc2Uigce7DmcoLLqV5KPIEIlhCAVzu7NQhn0uwGf8TIem0ug=
    -----END RSA PRIVATE KEY-----
{{ end }}
