{{- if and .Values.bank.enabled .Values.serviceAccounts.bank.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "openbanking.bank.labels" . | nindent 4 }}
  name: {{ template "openbanking.serviceAccountName.bank" . }}
{{ include "openbanking.namespace" . | indent 2 }}
  annotations:
{{ toYaml .Values.serviceAccounts.bank.annotations | indent 4 }}
{{- end -}}
