{{- if .Values.consentAdmin.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "openbanking.consentAdmin.labels" . | nindent 4 }}
  name: {{ template "openbanking.consentAdmin.fullname" . }}
{{ include "openbanking.namespace" . | indent 2 }}
spec:
  selector:
    matchLabels:
      {{- include "openbanking.consentAdmin.matchLabels" . | nindent 6 }}
  template:
    metadata:
    {{- if .Values.consentAdmin.podAnnotations }}
      annotations:
{{ toYaml .Values.consentAdmin.podAnnotations | indent 8 }}
    {{- end }}
      labels:
        {{- include "openbanking.consentAdmin.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ template "openbanking.serviceAccountName.bank" . }}
      {{- if .Values.consentAdmin.extraInitContainers }}
      initContainers:
{{ toYaml .Values.consentAdmin.extraInitContainers | indent 8 }}
      {{- end }}
{{- if .Values.consentAdmin.priorityClassName }}
      priorityClassName: "{{ .Values.consentAdmin.priorityClassName }}"
{{- end }}
      containers:
        - name: {{ template "openbanking.name" . }}-{{ .Values.consentAdmin.name }}
          image: "{{ .Values.consentAdmin.image.repository }}:{{ .Values.consentAdmin.image.tag }}"
          imagePullPolicy: "{{ .Values.consentAdmin.image.pullPolicy }}"
          env:
            - name: CERT_FILE
              value: /tls/tls.crt
            - name: KEY_FILE
              value: /tls/tls.key
            - name: ROOT_CA
              value: /tls/ca.crt
            - name: SYSTEM_ISSUER_URL
              value: {{ .Values.acpURL }}/default/system
            - name: BANK_URL
              value: http://{{ template "openbanking.bank.fullname" . }}:8070
            - name: LOGIN_AUTHORIZATION_SERVER_URL
              value: {{ .Values.acpURL }}
            - name: INTROSPECT_ISSUER_URL
              value: {{ .Values.acpURL }}/default/bank-admins
{{ toYaml .Values.consentAdmin.extraEnv | indent 12 }}
          args:
          {{- range $key, $value := .Values.consentAdmin.extraArgs }}
            - --{{ $key }}={{ $value }}
          {{- end }}
          ports:
            - containerPort: 8086
          resources:
{{ toYaml .Values.consentAdmin.resources | indent 12 }}
          volumeMounts:
            - mountPath: /tls
              name: tls
              readOnly: true
    {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      {{ toYaml .Values.imagePullSecrets | indent 2 }}
    {{- end }}
    {{- if .Values.consentAdmin.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.consentAdmin.nodeSelector | indent 8 }}
    {{- end }}
    {{- if .Values.consentAdmin.securityContext }}
      securityContext:
{{ toYaml .Values.consentAdmin.securityContext | indent 8 }}
    {{- end }}
    {{- if .Values.consentAdmin.tolerations }}
      tolerations:
{{ toYaml .Values.consentAdmin.tolerations | indent 8 }}
    {{- end }}
    {{- if .Values.consentAdmin.affinity }}
      affinity:
{{ toYaml .Values.consentAdmin.affinity | indent 8 }}
    {{- end }}
      volumes:
        - name: tls
          secret:
            secretName: {{ template "openbanking.fullname" . }}-tls
{{- end }}
