{{- if .Values.import.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "openbanking.fullname" . -}}-import
{{ include "openbanking.namespace" . | indent 2 }}
spec:
  backoffLimit: 3
  template:
    spec:
      containers:
        - name: acp-import
          image: cloudentity/openbanking-quickstart-configuration:latest
          args:
            - /app/main
            - --templates-dirs
            - /app/imports{{- if .Values.import.extraTemplate -}},/app/extra-imports{{- end }}
            - --tenant-url
            - {{ .Values.import.tenantUrl }}
            - --tenant
            - {{ .Values.import.tenant }}
            {{- if .Values.import.verbose }}
            - --verbose
            {{ end -}}
            - --variables-file
            - /app/vars/variables.yaml
            {{- if .Values.import.clientId }}
            - --client-id
            - {{ .Values.import.clientId }}
            {{ end }}
            {{- if .Values.import.clientSecret }}
            - --client-secret
            - {{ .Values.import.clientSecret }}
            {{- end }}
          volumeMounts:
            - name: variables
              mountPath: /app/vars
            {{- if .Values.import.extraTemplate }}
            - name: extra-templates
              mountPath: /app/extra-imports
            {{- end }}
      volumes:
        - name: variables
          configMap:
            name: {{ template "openbanking.fullname" . -}}-variables
        {{- if .Values.import.extraTemplate }}
        - name: extra-templates
          configMap:
            name: {{ template "openbanking.fullname" . -}}-extra-templates
        {{- end }}
      restartPolicy: Never
{{- end }}
