{{- if .Values.import.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    {{- include "openbanking.labels" . | nindent 4 }}
  name: {{ template "openbanking.fullname" . -}}-import
{{ include "openbanking.namespace" . | indent 2 }}
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded,before-hook-creation
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
        - name: {{ template "openbanking.name" . }}-{{ .Values.import.name }}
          image: "{{ .Values.import.image.repository }}:{{ .Values.import.image.tag }}"
          imagePullPolicy: "{{ .Values.import.image.pullPolicy }}"
          args:
            - /app/main
            - --templates-dirs
            - /app/imports{{- if .Values.import.extraTemplate -}},/app/extra-imports{{- end }}
            - --tenant-url
            - {{ .Values.acpURL }}/system
            - --tenant
            - {{ .Values.import.tenant }}
            {{- if .Values.import.verbose }}
            - --verbose
            {{ end -}}
            - --variables-file
            - /app/vars/variables.yaml
            {{- if .Values.import.clientId }}
            - --client-id
            - {{ .Values.import.clientId }}
            {{ end }}
            {{- if .Values.import.clientSecret }}
            - --client-secret
            - {{ .Values.import.clientSecret }}
            {{- end }}
          volumeMounts:
            - name: variables
              mountPath: /app/vars
            - mountPath: /tls
              name: tls
              readOnly: true
            {{- if .Values.import.extraTemplate }}
            - name: extra-templates
              mountPath: /app/extra-imports
            {{- end }}
      volumes:
        - name: tls
          secret:
            secretName: {{ template "openbanking.financroo.fullname" . }}-tls
        - name: variables
          configMap:
            name: {{ template "openbanking.fullname" . -}}-variables
        {{- if .Values.import.extraTemplate }}
        - name: extra-templates
          configMap:
            name: {{ template "openbanking.fullname" . -}}-extra-templates
        {{- end }}
      restartPolicy: Never
{{- end }}
