{{- if .Values.clientCredentials.create -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "kong-authorizer.clientCredentialsName" . }}
  labels:
    {{- include "kong-authorizer.labels" . | nindent 4 }}
data:
  clientID: {{ .Values.clientCredentials.clientID }}
  clientSecret: {{ .Values.clientCredentials.clientSecret }}
{{- end }}
