apiVersion: v1
kind: Service
metadata:
  name: {{ include "kong-authorizer.fullname" . }}
  labels:
    {{- include "kong-authorizer.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 9003
      name: http
  selector:
    {{- include "kong-authorizer.selectorLabels" . | nindent 4 }}
