{{- if .Values.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "acp.fullname" . }}
  labels:
    {{- include "acp.labels" . | nindent 4 }}
spec:
  duration: {{ .Values.certManager.duration }}
  renewBefore: {{ .Values.certManager.renewBefore }}
  usages:
    - digital signature
    - key encipherment
    - server auth
    - client auth
  privateKey:
    size: {{ .Values.certManager.privateKey.size }}
    algorithm: {{ .Values.certManager.privateKey.algorithm }}
  dnsNames:
    - {{ include "acp.fullname" . }}
    - {{ include "acp.fullname" . }}.{{ .Release.Namespace }}
    - {{ include "acp.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
    {{- with .Values.certManager.extraNames }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  secretName: {{ include "acp.fullname" . }}-tls
  issuerRef:
    name: {{ .Values.certManager.issuerRef.name }}
    kind: {{ .Values.certManager.issuerRef.kind }}
{{- end }}
