{{- if and .Values.faas.enabled .Values.faas.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (include "faas.serviceAccountName" .) .Values.faas.serviceAccount.name }}
  namespace: {{ .Values.faas.namespace.name }}
  labels:
    {{- include "acp.labels" . | nindent 4 }}
  {{- with .Values.faas.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
