{{- if and .Values.faas.enabled .Values.faas.networkPolicy.create }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "acp.fullname" . }}-faas
  namespace: {{ .Values.faas.namespace.name }}
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: {{ .Values.faas.networkPolicy.ipBlock.cidr }}
        {{- with .Values.faas.networkPolicy.ipBlock.except }}
        except:
          {{- toYaml . | nindent 8 }}
        {{- end }}
{{- end }}
