{{- if and .Values.faas.enabled .Values.faas.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.faas.namespace.name }}
  labels:
    {{- include "acp.labels" . | nindent 4 }}
{{- end }}
