{{- if and .Values.faas.enabled .Values.faas.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (include "faas.serviceAccountName" .) .Values.faas.serviceAccount.name }}
  namespace: {{ .Values.faas.namespace.name }}
  labels:
    {{- include "acp.labels" . | nindent 4 }}
  {{- with .Values.faas.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---
{{- if and .Values.faas.enabled (or (eq .Values.faas.provider "fission") (eq .Values.faas.provider "hybrid")) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ default (include "faas.serviceAccountName" .) .Values.faas.serviceAccount.name }}
rules:
  - apiGroups:
      - "fission.io"
    resources:
      - "packages"
      - "functions"
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ default (include "faas.serviceAccountName" .) .Values.faas.serviceAccount.name }}
subjects:
  - kind: ServiceAccount
    name: {{ default (include "faas.serviceAccountName" .) .Values.faas.serviceAccount.name }}
    namespace: {{ .Values.faas.namespace.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ default (include "faas.serviceAccountName" .) .Values.faas.serviceAccount.name }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "acp.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "acp.serviceAccountName" . }}
    namespace: {{.Release.Namespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ default (include "faas.serviceAccountName" .) .Values.faas.serviceAccount.name }}
{{- end }}
