{{- if and .Values.faas.enabled .Values.faas.environments.autoscaling.keda.enabled (not .Values.faas.environments.autoscaling.hpa.enabled) (or (eq .Values.faas.provider "docker") (eq .Values.faas.provider "hybrid")) }}
{{- range $envType, $envConfigs := .Values.faas.environments }}
{{- if or (eq $envType "node") (eq $envType "rego") }}
{{- range $version, $details := $envConfigs }}
{{- if $details.enabled }}
apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: {{ include "acp.fullname" $ }}-faas-{{ $envType }}-{{ $version }}
  namespace: {{ $.Values.faas.namespace.name }}
  labels:
    {{- include "acp.labels" $ | nindent 4 }}
spec:
  scaleTargetRef:
    deployment: {{ include "acp.fullname" $ }}-faas-{{ $envType }}-{{ $version }}
    service: {{ include "acp.fullname" $ }}-faas-{{ $envType }}-{{ $version }}
    port: {{ default $.Values.faas.environments.settings.ports.http (($details.ports).http) }}
  replicas:
    min: {{ $.Values.faas.environments.autoscaling.keda.minReplicas }}
    max: {{ $.Values.faas.environments.autoscaling.keda.maxReplicas }}
  scalingMetric:
    concurrency:
      targetValue: {{$.Values.faas.environments.autoscaling.keda.targetPendingRequests }}
  hosts:
    - {{ include "acp.fullname" $ }}-faas-{{ $envType }}-{{ $version }}-proxy
    - {{ include "acp.fullname" $ }}-faas-{{ $envType }}-{{ $version }}-proxy.{{ $.Values.faas.namespace.name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "acp.fullname" $ }}-faas-{{ $envType }}-{{ $version }}-proxy
  namespace: {{ $.Values.faas.namespace.name }}
  labels:
    {{- include "acp.labels" $ | nindent 4 }}
spec:
  type: ExternalName
  externalName: {{ $.Values.faas.environments.autoscaling.keda.interceptor_dns }}
---
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
