{{- if .Values.fission.enabled -}}
apiVersion: fission.io/v1
kind: Environment
metadata:
  name: nodejs
  namespace: {{ .Values.fission.namespace }}
    {{- with .Values.fission.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  version: 1
  imagepullsecret: {{ .Values.fission.imagepullsecret }}
  poolsize: {{ .Values.fission.poolsize }}
  terminationGracePeriod: 1
  runtime:
    image: docker.cloudentity.io/node-env:2
    podspec:
      containers:
        - name: nodejs
          imagePullPolicy: {{ .Values.fission.imagePullPolicy }}
      {{- with .Values.fission.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.fission.tolerations }}
      tolerations:
          {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.fission.resources }}
    resources:
      {{- toYaml . | nindent 4 }}
    {{- end }}


apiVersion: fission.io/v1
kind: Environment
metadata:
  name: rego
  namespace: {{ .Values.fission.namespace }}
    {{- with .Values.fission.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  version: 1
  imagepullsecret: {{ .Values.fission.imagepullsecret }}
  poolsize: {{ .Values.fission.poolsize }}
  terminationGracePeriod: 1
  runtime:
    image: docker.cloudentity.io/rego-env:2
    podspec:
      containers:
        - name: rego
          imagePullPolicy: {{ .Values.fission.imagePullPolicy }}
      {{- with .Values.fission.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.fission.tolerations }}
      tolerations:
          {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.fission.resources }}
    resources:
      {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
