{{- if .Values.fission.enabled -}}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: only-allow-internet
  namespace: {{ .Values.fission.namespace }}
spec:
  policyTypes:
    - Egress
  podSelector: {}
  egress:
    - to:
        - ipBlock:
            cidr: {{ .Values.fission.networkPolicy.ipBlock.cidr }}
            {{- with .Values.fission.networkPolicy.ipBlock.except }}
            except:
              {{- toYaml . | nindent 14 }}
            {{- end }}
---
apiVersion: fission.io/v1
kind: Environment
metadata:
  name: nodejs-v2
  namespace: {{ .Values.fission.namespace }}
    {{- with .Values.fission.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  version: 1
  imagepullsecret: {{ .Values.fission.imagepullsecret }}
  poolsize: {{ .Values.fission.poolsize }}
  terminationGracePeriod: 1
  runtime:
    image: {{ .Values.fission.images.node }}
    podspec:
      containers:
        - name: nodejs-v2
          imagePullPolicy: {{ .Values.fission.imagePullPolicy }}
          {{- with .Values.fission.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          startupProbe:
          {{- if .Values.fission.customStartupProbe }}
            {{ toYaml .Values.fission.customLivenessProbe | nindent 12 }}
          {{- else }}
            failureThreshold: 10
            periodSeconds: 10
            httpGet:
              path: /healthz
              port: 8888
          readinessProbe:
          {{- if .Values.fission.customReadinessProbe }}
            {{ toYaml .Values.fission.customReadinessProbe | nindent 12 }}
          {{- else }}
            failureThreshold: 3
            initialDelaySeconds: 3
            periodSeconds: 10
            timeoutSeconds: 0
            httpGet:
              path: /healthz
              port: 8888
          livenessProbe:
          {{- if .Values.fission.customLivenessProbe }}
            {{ toYaml .Values.fission.customLivenessProbe | nindent 12 }}
          {{- else }}
            failureThreshold: 3
            initialDelaySeconds: 3
            periodSeconds: 10
            timeoutSeconds: 0
            httpGet:
              path: /healthz
              port: 8888
      {{- with .Values.fission.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.fission.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.fission.tolerations }}
      tolerations:
          {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- with .Values.fission.resources }}
  resources:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: fission.io/v1
kind: Environment
metadata:
  name: rego-v2
  namespace: {{ .Values.fission.namespace }}
    {{- with .Values.fission.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  version: 1
  imagepullsecret: {{ .Values.fission.imagepullsecret }}
  poolsize: {{ .Values.fission.poolsize }}
  terminationGracePeriod: 1
  runtime:
    image: {{ .Values.fission.images.rego }}
    podspec:
      containers:
        - name: rego-v2
          imagePullPolicy: {{ .Values.fission.imagePullPolicy }}
          {{- with .Values.fission.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          startupProbe:
            failureThreshold: 10
            periodSeconds: 10
            httpGet:
              path: /healthz
              port: 8888
          readinessProbe:
            failureThreshold: 15
            initialDelaySeconds: 5
            periodSeconds: 1
            timeoutSeconds: 1
            httpGet:
              path: /healthz
              port: 8888
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 3
            periodSeconds: 10
            timeoutSeconds: 0
            httpGet:
              path: /healthz
              port: 8888
      {{- with .Values.fission.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.fission.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.fission.tolerations }}
      tolerations:
          {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- with .Values.fission.resources }}
  resources:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
