{{- if and .Values.faas.enabled (or (eq .Values.faas.provider "fission") (eq .Values.faas.provider "hybrid")) }}
{{- range $envType, $envConfigs := .Values.faas.environments }}
{{- if or (eq $envType "node") (eq $envType "rego") }}
{{- range $version, $details := $envConfigs }}
{{- if $details.enabled }}
apiVersion: fission.io/v1
kind: Environment
metadata:
  name: {{ include "acp.fullname" $ }}-faas-{{ $envType }}-v{{ $version }}
  namespace: {{ $.Values.faas.namespace.name }}
  labels:
    {{- include "acp.labels" $ | nindent 4 }}
  annotations:
    {{- $defaultAnnotations := $.Values.faas.environments.settings.annotations }}
    {{- $actualAnnotations := coalesce $details.annotations $defaultAnnotations }}
    {{- toYaml $actualAnnotations | nindent 4 }}
spec:
  version: 3
  poolsize: {{ default $.Values.faas.environments.settings.replicaCount $details.replicaCount }}
  terminationGracePeriod: 1
  runtime:
    image: {{ $details.image }}
    podspec:
      serviceAccountName: {{ default (include "faas.serviceAccountName" $ ) $.Values.faas.serviceAccount.name }}
      {{- with $.Values.faas.environments.settings.imagePullSecret }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ include "acp.fullname" $ }}-faas-{{ $envType }}-v{{ $version }}
          imagePullPolicy: {{ default $.Values.faas.environments.settings.imagePullPolicy $details.imagePullPolicy }}
          livenessProbe:
            {{- toYaml (default $.Values.faas.environments.settings.livenessProbe $details.livenessProbe) | nindent 12 }}
          readinessProbe:
            {{- toYaml (default $.Values.faas.environments.settings.readinessProbe $details.readinessProbe) | nindent 12 }}
          startupProbe:
            {{- toYaml (default $.Values.faas.environments.settings.startupProbe $details.startupProbe) | nindent 12 }}
          securityContext:
            {{- toYaml (default $.Values.faas.environments.settings.containerSecurityContext $details.containerSecurityContext) | nindent 12 }}
          env:
            {{- $defaultEnv := $.Values.faas.environments.settings.env }}
            {{- $actualEnv := coalesce $details.env $defaultEnv }}
            {{- toYaml $actualEnv | nindent 12 }}
          lifecycle:
            {{- toYaml (default $.Values.faas.environments.settings.lifecycle $details.lifecycle) | nindent 12 }}
          resources:
            {{- toYaml (default $.Values.faas.environments.settings.resources $details.resources) | nindent 12 }}
      securityContext:
        {{- toYaml $.Values.faas.environments.settings.podSecurityContext | nindent 8 }}
      nodeSelector:
        {{- toYaml (default $.Values.faas.environments.settings.nodeSelector $details.nodeSelector) | nindent 8 }}
      affinity:
        {{- toYaml (default $.Values.faas.environments.settings.affinity $details.affinity) | nindent 8 }}
      tolerations:
        {{- toYaml (default $.Values.faas.environments.settings.tolerations $details.tolerations) | nindent 8 }}
      topologySpreadConstraints:
        {{- toYaml (default $.Values.faas.environments.settings.topologySpreadConstraints $details.topologySpreadConstraints) | nindent 8 }}
---
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
