{{- range $environments := .Values.fission.environments }}

apiVersion: fission.io/v1
kind: Environment
metadata:
  name: {{ $environments.name }}
    {{- with $environments.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  version: {{ $environments.version }}
  imagepullsecret: {{ $environments.imagepullsecret }}
  poolsize: {{ $environments.pollsize }}
  terminationGracePeriod: 1
  runtime:
    image: {{ $environments.image }}
    podspec:
      containers:
        - name: {{ $environments.name }}
          imagePullPolicy: {{ $environments.imagePullPolicy }}
      {{- with $environments.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $environments.tolerations }}
      tolerations:
          {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with $environments.resources }}
    resources:
      {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
