{{- with .Values.fission.environments }}
apiVersion: fission.io/v1
kind: Environment
metadata:
  name: {{ .name }}
  annotations:
     {{ toYaml .annotations | indent 8 }}
spec:
  version: {{ .version }}
  imagepullsecret: {{ .imagepullsecret }}
  poolsize: {{ .pollsize }}
  terminationGracePeriod: 1
  runtime:
    image: {{ .image }}
    podspec:
      containers:
        - name: {{ .name }}
          imagePullPolicy: {{ .imagePullPolicy }}
      affinity:
        {{- with .affinity }}
          {{- toYaml . | nindent 4 }}
        {{- end }}
      tolerations:
      {{- with .tolerations }}
          {{ toYaml . | nindent 8 }}
      {{- end }}
  resources:
    {{- with .resources }}
      {{- toYaml . | nindent 4 }}
    {{- end }}

{{- end }}
