{{- range $environments := .Values.fission.environments }}

apiVersion: fission.io/v1
kind: Environment
metadata:
  name: {{ $environments.name }}
  annotations:
spec:
  version: {{ $environments.version }}
  imagepullsecret: {{ $environments.imagepullsecret }}
  poolsize: {{ $environments.pollsize }}
  terminationGracePeriod: 1
  runtime:
    image: {{ $environments.image }}
    podspec:
      containers:
        - name: {{ $environments.name }}
          imagePullPolicy: {{ $environments.imagePullPolicy }}
      affinity:
        {{- with $environments.affinity }}
          {{- toYaml . | nindent 4 }}
        {{- end }}
      tolerations:
      {{- with $environments.tolerations }}
          {{ toYaml . | nindent 8 }}
      {{- end }}
  resources:
    {{- with $environments.resources }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
