{{- if .Values.secretConfig.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "acp.secretConfig" . }}
  labels:
    {{- include "acp.labels" . | nindent 4 }}
  {{- with .Values.secretConfig.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
stringData:
  config.yaml: |
    {{- with .Values.secretConfig.data }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
