apiVersion: v1
kind: Service
metadata:
  name: {{ include "acp.fullname" . }}
  labels:
    {{- include "acp.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ include "acp.portNumber" . }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 9000
      targetPort: metrics
      protocol: TCP
      name: metrics
    - port: 9443
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "acp.selectorLabels" . | nindent 4 }}
