{{- if and  .Values.certificate.cert .Values.certificate.key (not .Values.certManager.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "acp.fullname" . }}-tls
  labels:
    {{- include "acp.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  {{- with .Values.certificate }}
  tls.crt: {{ .cert | b64enc }}
  tls.key: {{ .key | b64enc }}
  {{- end }}
{{- end }}
