{{- if and .Values.certificate.cert .Values.certificate.key (not .Values.certManager.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "acp.fullname" . }}-tls
  labels:
    {{- include "acp.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  {{- with .Values.certificate }}
  tls.crt: {{ .cert | b64enc }}
  tls.key: {{ .key | b64enc }}
  {{- end }}
{{- end }}
{{- range .Values.ingress.tlsSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  labels:
    {{- include "acp.labels" $ | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .cert | b64enc }}
  tls.key: {{ .key | b64enc }}
{{- end }}
---
{{- if .Values.ingressMtls.enabled }}
{{- with .Values.ingressMtls.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  labels:
    {{- include "acp.labels" $ | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .cert | b64enc }}
  tls.key: {{ .key | b64enc }}
  ca.crt: {{ .caCert | b64enc }}
{{- end }}
{{- end }}
