{{- if and .Values.workers.enabled .Values.workers.autoscaling.enabled }}
{{- if $.Capabilities.APIVersions.Has "autoscaling/v2/HorizontalPodAutoscaler" }}
apiVersion: autoscaling/v2
{{- else -}}
apiVersion: autoscaling/v2beta2
{{- end }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "acp.fullname" . }}-workers
  labels:
    {{- include "acp.workers.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "acp.fullname" . }}-workers
  minReplicas: {{ .Values.workers.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.workers.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.workers.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.workers.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.workers.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .Values.workers.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
  {{- with .Values.workers.autoscaling.behavior }}
  behavior:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
