{{- if .Values.workers.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "acp.fullname" . }}-workers
  labels:
    {{- include "acp.workers.labels" . | nindent 4 }}
  {{- with .Values.workers.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.workers.autoscaling.enabled }}
  replicas: {{ .Values.workers.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "acp.workers.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.workers.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "acp.workers.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: data
          configMap:
            name: {{ include "acp.configName" . }}
        - name: tls
          projected:
            defaultMode: 384
            sources:
            - secret:
                name: {{ include "acp.fullname" . }}-tls
            {{- if ((.Values.client).rootCa) }}
            - secret:
                name: {{ include "acp.fullname" . }}-client-tls
            {{- end }}
        - name: secret
          secret:
            secretName: {{ include "acp.secretConfig" . }}
      serviceAccountName: {{ include "acp.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
          {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
            - name: SERVER_DISABLE_ASYNC_PROCESSING
              value: "false"
          ports:
            - name: http
              containerPort: {{ include "acp.portNumber" . }}
              protocol: TCP
            - name: metrics
              containerPort: 9000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /alive
              {{- if .Values.tlsDisabled }}
              scheme: HTTP
              {{- else }}
              scheme: HTTPS
              {{- end }}
              port: {{ include "acp.portNumber" . }}
            initialDelaySeconds: 3
            failureThreshold: 1
            periodSeconds: 10
            timeoutSeconds: 10
          startupProbe:
            httpGet:
              path: /alive
              {{- if .Values.tlsDisabled }}
              scheme: HTTP
              {{- else }}
              scheme: HTTPS
              {{- end }}
              port: {{ include "acp.portNumber" . }}
            failureThreshold: 10
            periodSeconds: 10
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /alive
              {{- if .Values.tlsDisabled }}
              scheme: HTTP
              {{- else }}
              scheme: HTTPS
              {{- end }}
              port: {{ include "acp.portNumber" . }}
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 10
          volumeMounts:
            - mountPath: /data
              name: data
              readOnly: true
            - mountPath: /tls
              name: tls
              readOnly: true
            - mountPath: /secret
              name: secret
              readOnly: true
          resources:
            {{- toYaml .Values.workers.resources | nindent 12 }}
      {{- with .Values.workers.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.workers.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.workers.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.workers.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
