{{- if .Values.consentPage.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "openbanking.consentPage.labels" . | nindent 4 }}
  name: {{ template "openbanking.consentPage.fullname" . }}
{{ include "openbanking.namespace" . | indent 2 }}
spec:
  selector:
    matchLabels:
      {{- include "openbanking.consentPage.matchLabels" . | nindent 6 }}
  template:
    metadata:
    {{- if .Values.consentPage.podAnnotations }}
      annotations:
{{ toYaml .Values.consentPage.podAnnotations | indent 8 }}
    {{- end }}
      labels:
        {{- include "openbanking.consentPage.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ template "openbanking.serviceAccountName.consentPage" . }}
      {{- if .Values.consentPage.extraInitContainers }}
      initContainers:
{{ toYaml .Values.consentPage.extraInitContainers | indent 8 }}
      {{- end }}
{{- if .Values.consentPage.priorityClassName }}
      priorityClassName: "{{ .Values.consentPage.priorityClassName }}"
{{- end }}
      containers:
        - name: {{ template "openbanking.name" . }}-{{ .Values.consentPage.name }}
          image: "{{ .Values.consentPage.image.repository }}:{{ .Values.consentPage.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: "{{ .Values.consentPage.image.pullPolicy }}"
          env:
            - name: CERT_FILE
              value: /tls/tls.crt
            - name: KEY_FILE
              value: /tls/tls.key
            - name: ROOT_CA
              value: /tls/ca.crt
            - name: ISSUER_URL
              value: {{ .Values.acpURL }}/default/system
            - name: BANK_URL
            {{- if .Values.bankURL }}
              value: {{ .Values.bankURL }}
            {{- else }}
              value: http://{{ template "openbanking.bank.fullname" . }}:8070
            {{- end }}
{{ toYaml .Values.consentPage.extraEnv | indent 12 }}
          args:
          {{- range $key, $value := .Values.consentPage.extraArgs }}
            - --{{ $key }}={{ $value }}
          {{- end }}
          ports:
            - containerPort: 8080
          resources:
{{ toYaml .Values.consentPage.resources | indent 12 }}
          volumeMounts:
            - mountPath: /app/data
              name: data
            - mountPath: /tls
              name: tls
              readOnly: true
            - mountPath: /app/templates/custom
              name: templates
    {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      {{ toYaml .Values.imagePullSecrets | indent 2 }}
    {{- end }}
    {{- if .Values.consentPage.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.consentPage.nodeSelector | indent 8 }}
    {{- end }}
    {{- if .Values.consentPage.securityContext }}
      securityContext:
{{ toYaml .Values.consentPage.securityContext | indent 8 }}
    {{- end }}
    {{- if .Values.consentPage.tolerations }}
      tolerations:
{{ toYaml .Values.consentPage.tolerations | indent 8 }}
    {{- end }}
    {{- if .Values.consentPage.affinity }}
      affinity:
{{ toYaml .Values.consentPage.affinity | indent 8 }}
    {{- end }}
      volumes:
        - name: data
          emptyDir: {}
        - name: tls
          secret:
            secretName: {{ template "openbanking.consentPage.fullname" . }}-tls
        - name: templates
          configMap:
            name: {{ if .Values.consentPage.templatesConfigMapOverrideName }}{{ .Release.Name }}-{{ .Values.consentPage.templatesConfigMapOverrideName }}{{- else }}{{ template "openbanking.consentPage.fullname" . }}-templates{{- end }}
{{- end }}
