{{- if and .Values.consentPage.enabled .Values.serviceAccounts.consentPage.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "openbanking.consentPage.labels" . | nindent 4 }}
  name: {{ template "openbanking.serviceAccountName.consentPage" . }}
{{ include "openbanking.namespace" . | indent 2 }}
  annotations:
{{ toYaml .Values.serviceAccounts.consentPage.annotations | indent 4 }}
{{- end -}}
