{{- if .Values.config.create -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "acp-cd.configName" . }}
  labels:
    {{- include "acp-cd.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- if or .Values.certManager.enabled ((.Values.client).rootCa) }}
    client:
      root_ca: /tls/ca.crt
    {{- end }}
  extraconfig.yaml: |
    {{- with .Values.config.data }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "acp-cd.fullname" . }}-import
  labels:
    {{- include "acp-cd.labels" . | nindent 4 }}
data:
  seed.yaml: |
    {{- with .Values.data }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
