apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "acp-cd.fullname" . }}
  labels:
    {{- include "acp-cd.labels" . | nindent 4 }}
data:
  seed.yaml: |
    {{- with .Values.data }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
