{{- if ((.Values.client).rootCa) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "acp-cd.fullname" . }}-client-tls
  labels:
    {{- include "acp-cd.labels" . | nindent 4 }}
data:
  ca.crt: {{ .Values.client.rootCa | b64enc }}
{{- end }}
