{{- if and .Values.financroo.enabled .Values.serviceAccounts.financroo.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "openbanking.financroo.labels" . | nindent 4 }}
  name: {{ template "openbanking.serviceAccountName.financroo" . }}
{{ include "openbanking.namespace" . | indent 2 }}
  annotations:
{{ toYaml .Values.serviceAccounts.financroo.annotations | indent 4 }}
{{- end -}}
