name: kong-authorizer chart test
on:
  push:
    tags-ignore:
      - "*"
  pull_request:
    paths:
      - 'charts/kong-authorizer/**'
      - 'tests/**'

env:
  CHART: kong-authorizer

jobs:
  lint:
    name: Linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Helm lint
        run: make helm-lint
      - name: Kubeeval lint
        run: make lint-kubeeval
      - name: Check kubernetes APIs
        run: make check-kube-apis
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PWD: ${{ secrets.DOCKER_PWD }}
        run: make prepare
      - name: Verify
        run: CHART=acp make verify
      - name: install-kong
        run: make install-kong
      - name: install
        run: NAMESPACE=kong-authorizer make install
      - name: wait
        run: NAMESPACE=kong-authorizer make wait-for-daemonset
      # TODO enable after service discovery disable option will be available
      # - name: Helm tests
      #   run: NAMESPACE=kong-authorizer make helm-test
      - name: Debug
        if: failure()
        run: make debug
