name: kong-authorizer chart test
on:
  push:
    tags-ignore:
      - "*"
  pull_request:

env:
  CHART: kong-authorizer

jobs:
  lint:
    name: Linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Helm lint
        run: make helm-lint
      - name: Kubeeval lint
        run: make lint-kubeeval
      - name: Check kubernetes APIs
        run: make check-kube-apis
