name: kong-authorizer chart test
on:
  push:
    tags-ignore:
      - "*"

env:
  CHART: kong-authorizer

jobs:
  lint:
    name: Linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Helm lint
        run: make helm-lint
