name: kube-acp-stack chart test
on:
  push:
    tags-ignore:
      - "*"
  pull_request:
    paths:
      - 'charts/kube-acp-stack/**'
      - 'charts/acp/**'
      - 'tests/**'

env:
  CHART: kube-acp-stack

jobs:
  lint:
    name: Linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Helm lint
        run: make helm-lint
      - name: Kubeeval lint
        run: make lint-kubeeval
  acp-dependency-version:
    name: Check acp dependency version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Compare acp chart dependency version
        run: make check-acp-charts-version
