name: kube-acp-stack chart test
on:
  push:
    branches-ignore:
      - "master"
    tags-ignore:
      - "*"

jobs:
  lint:
    name: Linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Helm lint
        run: make helm-lint CHART=kube-acp-stack
  acp-dependency-version:
    name: Check acp dependency version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Compare acp chart dependency version
        run: make check-acp-charts-version
