name: Publish
on:
  push:
    branches:
      - "master"
    paths:
      - "**/Chart.yaml"
  pull_request:

jobs:
  acp:
    needs: lint
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2

      - name: Helm package charts/acp
        run: helm package charts/acp

      - uses: jfrog/setup-jfrog-cli@v1
        env:
          JF_ARTIFACTORY_1: ${{ secrets.JF_ARTIFACTORY_SECRET_1 }}

      - name: Publish
        run: jfrog rt u *.tgz acp-helm-charts

  kube-acp-stack:
    needs: acp
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2

      - name: Helm package charts/kube-acp-stack
        run: helm package -u charts/kube-acp-stack

      - uses: jfrog/setup-jfrog-cli@v1
        env:
          JF_ARTIFACTORY_1: ${{ secrets.JF_ARTIFACTORY_SECRET_1 }}

      - name: Publish
        run: jfrog rt u *.tgz acp-helm-charts

  openbanking:
    needs: lint
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2

      - name: Helm package charts/openbanking
        run: helm package charts/openbanking

      - uses: jfrog/setup-jfrog-cli@v1
        env:
          JF_ARTIFACTORY_1: ${{ secrets.JF_ARTIFACTORY_SECRET_1 }}

      - name: Publish
        run: jfrog rt u *.tgz acp-helm-charts

  istio-authorizer:
    needs: lint
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2

      - name: Helm package charts/istio-authorizer
        run: helm package charts/istio-authorizer

      - uses: jfrog/setup-jfrog-cli@v1
        env:
          JF_ARTIFACTORY_1: ${{ secrets.JF_ARTIFACTORY_SECRET_1 }}

      - name: Publish
        run: jfrog rt u *.tgz acp-helm-charts
