name: release branch helm charts

on:
  repository_dispatch:
    types: [release-branch-helm-charts]

env:
  ACP_VERSION: ${{ github.event.client_payload.acp_version }}

jobs:
  release-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set ACP version
        run: sed -i.bak "s/ACP_VERSION ?=.*/ACP_VERSION ?= ${{ env.ACP_VERSION }}/" Makefile && rm Makefile.bak

      - name: ACP version in charts
        run: CI=true make bump-acp-version
