name: update helm chart default values
on:
  workflow_dispatch:
    inputs:
      chart:
        type: choice
        description: Chart to update
        options: 
          - acp-cd
          - acp
          - istio-authorizer
          - kube-acp-stack
          - openbanking
      key:
        description: "Key to update"
        required: true
      value:
        description: "Value to set"
        required: true 
jobs:
  set-new-default-value:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.CLOUDENTITY_CI_TOKEN }}
      - name: Set key & value
        uses: mikefarah/yq@v4.34.1
        with:
          cmd: yq '${{ inputs.key }} = "${{ inputs.value }}"' charts/${{ inputs.chart }}/values.yaml > charts/${{ inputs.chart }}/values-updated.yaml
      - name: Keep empty lines
        run: |
          diff -U0 -w -b --ignore-blank-lines charts/${{ inputs.chart }}/values.yaml charts/${{ inputs.chart }}/values-updated.yaml > charts/${{ inputs.chart }}/values.yaml.diff || true
          patch charts/${{ inputs.chart }}/values.yaml < charts/${{ inputs.chart }}/values.yaml.diff
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.CLOUDENTITY_CI_TOKEN }}
          branch: "feature/update-${{ inputs.chart }}-${{ inputs.key }}"
          add-paths: "charts/${{ inputs.chart }}/values.yaml"
          delete-branch: true
          title: "[${{ inputs.chart }}] Update default value of ${{ inputs.key }}"
          commit-message: "Update default values"
          body-path: .github/HELM_VALUE_UPDATE_PULL_REQUEST_TEMPLATE.md
          labels: "auto-upgrade"
          team-reviewers: cloudentity/devops
