name: update helm chart default values
on:
  workflow_dispatch:
    inputs:
      chart:
        type: choice
        description: Chart to update
        options: 
          - acp-cd
          - acp
          - istio-authorizer
          - kube-acp-stack
          - openbanking
      key:
        description: "Key to update"
        required: true
      value:
        description: "Value to set"
        required: true 
jobs:
  set-new-default-value:
    runs-on: ubuntu-latest
    steps:
      - name: set-key-value
        uses: mikefarah/yq@v4.34.1
        with:
          cmd: yq -i '${{ inputs.key }} = "${{ inputs.value }}"' charts/${{ inputs.chart }}/values.yaml
