name: Update FaaS Images

on:
  workflow_dispatch:
    inputs:
      node_v4:
        description: 'Update Node v4 (true/false)'
        required: true
        default: 'true'
      node_v5:
        description: 'Update Node v5 (true/false)'
        required: true
        default: 'false'
      rego_v5:
        description: 'Update Rego v5 (true/false)'
        required: true
        default: 'true'
      tag:
        description: 'Image Tag'
        required: true
        default: 'testing'

jobs:
  update-faas-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.CLOUDENTITY_CI_TOKEN }}
      - name: Set Environment Variables
        run: |
          echo "NODE_V4=${{ github.event.inputs.node_v4 }}" >> $GITHUB_ENV
          echo "NODE_V5=${{ github.event.inputs.node_v5 }}" >> $GITHUB_ENV
          echo "REGO_V5=${{ github.event.inputs.rego_v5 }}" >> $GITHUB_ENV
          echo "TAG=${{ github.event.inputs.tag }}" >> $GITHUB_ENV
      - name: Update Helm Values File
        shell: bash
        run: |
          environments=("NODE_V4" "NODE_V5" "REGO_v5")
          for env in "${environments[@]}"; do
          echo "env: $env"
            update=$(eval echo "\$$(echo ${env^^})")
            echo "update: $update"
            if [ "$update" = "true" ]; then
              version=${env##*_}
              component=${env%%_*}
              echo "version: $version"
              echo "component: $component"
              yq e -i ".faas.environments.$component.$version.image = \"${component}-env:v${version}-$TAG\"" charts/acp/values.yaml
            fi
          done
          cat charts/acp/values.yaml

          #      - name: Create Pull Request
          #        uses: peter-evans/create-pull-request@v5
          #        with:
          #          token: ${{ secrets.CLOUDENTITY_CI_TOKEN }}
          #          branch: "feature/update-faas-images"
          #          delete-branch: ttru
          #          title: "Update FaaS images"
          #          body-path: .github/HELM_VALUE_UPDATE_PULL_REQUEST_TEMPLATE.md
          #          labels: "auto-upgrade"
          #          team-reviewers: cloudentity/devops
